### ISSUE TITLE
Increase node size from 8 CPU to 16 CPU

### ISSUE THREAD

**Issue by howardjohn** [istio/test-infra#1766]
Currently our jobs run with 3cpu request, 5cpu limit, on 8 core machines. This means we can have at most 2 tests running per machine. We have 60 machines, so 120 concurrent tests total.

For the same cost, we can get 30 16 core CPUs. This would allow 5 tests per machine, so 150 concurrent tests total.

Once we make this transition, we can increase the CPU limit. This would allow tests to run much faster and experience less flakes.

Steps

1. done - remove 10 nodes and replace with 5 16-core nodes.
2. done - Wait a few days to verify this doesn't have unexpected negative impact
3. done - Transition rest of nodes over to 16 cores
4. Update resource limits

**Comment by howardjohn** [comment]
@clarketm thoughts? I can do this if you give me the go-ahead

**Comment by clarketm** [comment]
@howardjohn 
This migration plan SGTM. You have access to the build cluster's `test-pool`, so if you are familiar and comfortable with the change, I say go for it. If you need any assistance or would like my help let me know. Please remember to post an update in slack when the change is started and/or complete.  

Since you will be creating a *new* node pool just remember to add the `testing: test-pool` Kubernetes label, or alternatively, create a new label and add the node selector to the jobs you want to run on the *new* 16 core CPU node-pool. For the existing node-pool you should be able to easily shrink down with minimal/no downtime one the new pool is healthy. 👍

**Comment by howardjohn** [comment]
Thanks! I'll do this next week or sometime after we get the 1.3 release out

**Comment by howardjohn** [comment]
> Wait a few days to verify this doesn't have unexpected negative impact

This has happened, I would feel confident switching over now. Luckily I probably won't get around to it for a few more days so we can let it soak some more

**Comment by clarketm** [comment]
> Luckily I probably won't get around to it for a few more days so we can let it soak some more

If there is any urgency let me know and I can make the switch, otherwise SGTM to give it more time.

**Comment by howardjohn** [comment]
looks like test time went from 13-15 min to 9-11 min! going to roll out change to all our other jobs as well
