### ISSUE TITLE
Tide: plank.allow_cancellations is deprecated

### ISSUE THREAD

**Issue by chases2** [istio/test-infra#2115]
```
{
  component: "tide"   
  file: "prow/config/config.go:1237"   
  func: "k8s.io/test-infra/prow/config.parseProwConfig"   
  level: "warning"   
  msg: "The `plank.allow_cancellations` setting is deprecated. It will be removed and set to always true in March 2020"   
 }
```

**Comment by clarketm** [comment]
Looks like a bug in the Prow warning logic :confused: , because Istio does not set the `plank.allow_cancellations` field in the [config.yaml](https://github.com/istio/test-infra/blob/22f8e7d6e7c4603815446bdd9aeaeaeec8872551/prow/config.yaml#L3-L20). 

---

Oh, apparently [**not setting it to true**](https://github.com/kubernetes/test-infra/blob/93c6c43b21f60e4ff2f7955f6fd7660d2290c6bb/prow/config/config.go#L1261-L1263) is the warning/problem. This makes sense to enable as a feature anyway: #2155

**Comment by clarketm** [comment]
ref: https://github.com/kubernetes/test-infra/issues/15502
