### ISSUE TITLE
prow issues

### ISSUE THREAD

**Issue by ldemailly** [istio/test-infra#277]
a couple of prow issues I noticed:
- [ ] it only shows "Build Still Running!" while in progress, we need to see the current log (and stages)
- [ ] once done, the raw build log seems to display as html instead of text https://storage.googleapis.com/istio-prow/pull/istio_istio/460/istio-presubmit/45/build-log.txt - strangely it's fine when using curl... so User-Agent magic played by googleapis ?
- [ ] it says "prow/istio-presubmit.sh — Skipped" on https://github.com/istio/istio/pull/470 and I can't seem to tell why (probably because it's a branch of a branch? but jenkins does run fine)
- [ ] can't seem to find PR log or other overview (maybe a permission issue?) from https://k8s-gubernator.appspot.com/builds/istio-prow/pull/istio_istio/460/istio-presubmit/ ? tried https://k8s-gubernator.appspot.com/builds/istio-prow/pull/istio_istio/ but nothing really working there

<img width="838" alt="screen shot 2017-07-16 at 2 01 29 am" src="https://user-images.githubusercontent.com/3664595/28246268-c0a02264-69ca-11e7-8b8d-b79bc0b9ec4b.png">
<img width="762" alt="screen shot 2017-07-16 at 2 01 41 am" src="https://user-images.githubusercontent.com/3664595/28246269-c2aad086-69ca-11e7-8069-c3e23151698f.png">

This being said It's great already it builds with /ok-to-build without having the submitter in the org!

**Comment by ldemailly** [comment]
somehow I can't assign so cc @nlandolfi and @sebastienvas

**Comment by ldemailly** [comment]
also seems more flacky - I got 2x failure only prow

**Comment by ldemailly** [comment]
for instance: https://github.com/istio/istio/pull/470#issuecomment-317214905

**Comment by sebastienvas** [comment]
Prow currently only run on master. I don t hink Prow is actually more flaky as Prow and the e2e testing cluster are in the same zone. The only difference that I can spot is that Jenkins is using 1.6.0 while Prow is using 1.6.4.

**Comment by nlandolfi** [comment]
I think we have resolved these over the past few weeks and also through clarifications in conversation but let me know if not!

1. We pointed out that prow.istio.io has the logs when the job is running. We are working on having the Github status link go directly to these live logs while the job is running, and then link to the durable storage logs (Gubernator) once the build has completed. This relies on a [slight change](https://github.com/kubernetes/test-infra/pull/3876) to the upstream Prow project.

2. Yes I believe it is user-agent magic. I think we talked about how ctl-f works, and you can curl if you want the text. We also made the bucket public to GCS web ui, for browsing.

3. Yes, that was skipped because we were only running presubmits to master. This makes sense from a resource conservation point of view, but perhaps not from the development point of view. Which branches we run jobs for is specified in the prow configuration "branches" block. I enabled it on all branches for istio/istio with [this PR](https://github.com/istio/test-infra/pull/290/files). 

4. Those links are now working. let me know if still having issues.
