### ISSUE TITLE
populate deck.additional_allowed_buckets with at least one bucket

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#3108]
```yaml

{ "msg": "skipping storage-path validation because `in_repo_config` is enabled, but `deck.additional_allowed_buckets` empty. (Note: Validation will be enabled by default in January 2021. To disable this message, populate `deck.additional_allowed_buckets` with at least one storage bucket. When `deck.additional_allowed_buckets` is populated, this message will be disabled.)", "component": "deck", "func": "k8s.io/test-infra/prow/logrusutil.ThrottledWarnf", "file": "prow/logrusutil/logrusutil.go:138", "level": "warning" }
```

**Comment by chaodaiG** [comment]
This warning says it will start to validate bucket name from `inrepoconfig`, aka prowjobs defined in another repo other than istio/test-infra, and will fail if the bucket name used is not defined in [`additional_allowed_buckets`](https://github.com/kubernetes/test-infra/blob/76ffa49602f9afdfa6067d513c6ad5b456cfac05/prow/config/config.go#L730).

I have taken a quick look and there doesn't seem to be a repo under `istio` using `inrepoconfig` yet, did I miss anything @howardjohn ?

If that's the case we might just explicitly pass in [`skip_storage_path_validation`](https://github.com/kubernetes/test-infra/blob/76ffa49602f9afdfa6067d513c6ad5b456cfac05/prow/config/config.go#L726), otherwise please add the additional `bucket name` under [`additional_allowed_buckets`](https://github.com/kubernetes/test-infra/blob/76ffa49602f9afdfa6067d513c6ad5b456cfac05/prow/config/config.go#L730)

**Comment by fejta** [comment]
We'll just not allow any additional buckets for the time being.
