### ISSUE TITLE
Tmp dir path should not be hard coded

### ISSUE THREAD

**Issue by sebastienvas** [istio/test-infra#444]
https://github.com/istio/test-infra/blob/master/toolbox/githubctl/main.go#L46

This is harcoded to tmp/release instead of /tmp/release, but I think this temp dir should be created using https://golang.org/pkg/io/ioutil/#TempDir, that way we don't have to deal with directory not being present.

**Comment by chxchx** [comment]
This is intentional. If you take a look at https://github.com/istio/istio/blob/master/release/create_release_archives.sh#L44, the `mkdir -p` means `no error if existing, make parent directories as needed`. The ` tmp/release` is actually a sub folder of the istio repo we just cloned. After we upload arttifacts and create a PR to update the download script, the entire istio local repo gets removed.
