### ISSUE TITLE
/lgtm comment with github approval fails to mark lgtm label?

### ISSUE THREAD

**Issue by jmuk** [istio/test-infra#449]
My recent PRs https://github.com/istio/mixer/pull/1193 and https://github.com/istio/mixer/pull/1196 look like istio-merge-robot fails to mark `lgtm` label even though a reviewer said `/lgtm`.

I suspect that the comment comes at the same time with github approval, and the merge-bot misses parsing the comment content in such case?

**Comment by yutongz** [comment]
This is a known issue from github webhook. The explanation is :
1. Github fails to send out events through webhook to prow (which shows up as "istio-testing") so that prow has no idea about "/lgtm".  Prow uses webhook as a matter of fact its' a CI.
2. Mungegithub (which shows up as "istio-merge-robot") works in a different way. It seeks for specific comments every circle. That explains why "approved" label is added.

The reason of GitHub webhook missing events is unknown. For now the solution is to comment "/lgtm" until istio-testing actually add "lgtm" label. Normally istio-testing should response in seconds.

**Comment by yutongz** [comment]
Believe fixed. Config webhook to send "pull request review" event to Prow.
https://github.com/istio/test-infra/pull/542
