### ISSUE TITLE
dependency updater insists on token file

### ISSUE THREAD

**Issue by ldemailly** [istio/test-infra#483]
$ ./bazel-bin/toolbox/deps_update/deps_update --repo=istio --hub=gcr.io/istio-testing
2017/09/12 03:01:56 token_file not provided

should work just using git commands when run by a human

**Comment by ldemailly** [comment]
or use GITHUB_TOKEN env var

**Comment by chxchx** [comment]
A token is required since the script make couple of GitHub REST API calls and must be authenticated using the oauth token, so it works slightly different from git command in shell. 

I see that both env var and token file would work just fine as valid carriers of the token but I was not sure about the advantage of switching to env var at the moment. Perhaps a P2 in Q4.

**Comment by ldemailly** [comment]
it's fine just some other tools (jekyll and some other I forgot) already rely on env

but file is fine
